# Generated by Django 4.0.4 on 2022-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Browser', models.CharField(max_length=100)),
            ],
        ),
    ]
