# Generated by Django 4.0.4 on 2022-07-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_limited_count_alter_limited_browser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limited',
            old_name='Browser',
            new_name='browser',
        ),
    ]
