# Generated by Django 4.0.4 on 2022-07-13 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_rename_browser_limited_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='limited',
            name='history',
            field=models.TextField(null=True),
        ),
    ]
