# Generated by Django 4.0.4 on 2022-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0005_limited_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='limited',
            name='history',
        ),
    ]
