# Generated by Django 4.0.4 on 2022-07-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0006_history_remove_limited_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-history']},
        ),
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.TextField(),
        ),
    ]
