# Generated by Django 4.0.4 on 2022-07-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0007_alter_history_options_alter_history_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
        migrations.AddField(
            model_name='limited',
            name='operating_system',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='limited',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
