# Generated by Django 4.0.4 on 2022-07-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0008_alter_history_options_limited_operating_system_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limited',
            name='version',
        ),
        migrations.AddField(
            model_name='limited',
            name='version_string',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
