# Generated by Django 4.0.4 on 2022-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0009_remove_limited_version_limited_version_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedIp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
