# Generated by Django 4.0.4 on 2022-07-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0010_limitedip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='history',
            new_name='used_short_url',
        ),
    ]
