# Generated by Django 4.0.4 on 2022-07-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0011_rename_history_history_used_short_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Limited',
            new_name='UserAgent',
        ),
        migrations.RenameModel(
            old_name='LimitedIp',
            new_name='UserAgentIp',
        ),
    ]
