# Generated by Django 4.0.4 on 2022-07-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0012_rename_limited_useragent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='new_url',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
