# Generated by Django 4.0.4 on 2022-07-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0013_shortener_new_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='new_url',
        ),
    ]
