# Generated by Django 4.0.4 on 2022-07-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0014_remove_shortener_new_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragent',
            old_name='version_string',
            new_name='operating_version_string',
        ),
    ]
