# Generated by Django 4.0.4 on 2022-07-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0016_history_used_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAgentIp',
        ),
        migrations.AddField(
            model_name='useragent',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
