# Generated by Django 4.0.4 on 2022-07-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0017_delete_useragentip_useragent_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragent',
            old_name='ip_address',
            new_name='user_ip_address',
        ),
    ]
