# Generated by Django 4.0.4 on 2022-07-27 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0018_rename_ip_address_useragent_user_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='ip_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urlshortener.useragent'),
        ),
    ]
