# Generated by Django 4.0.4 on 2022-07-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0019_history_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='ip_address',
            new_name='user_ip_address',
        ),
    ]
