# Generated by Django 4.0.4 on 2022-07-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0020_rename_ip_address_history_user_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user_ip_address',
        ),
        migrations.AddField(
            model_name='history',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
