# Generated by Django 4.0.4 on 2022-07-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0021_remove_history_user_ip_address_history_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
